# output paths for hydra logs
run:
  dir: ../../scratch/logs/training/runs/${run_name}/${now:%Y-%m-%d}_${now:%H-%M-%S}
  # dir: scratch/logs/training/runs/${run_name}/${now:%Y-%m-%d}_${now:%H-%M-%S}

sweep:
  dir: ../../scratch/logs/training/multiruns/${run_name}/${now:%Y-%m-%d}_${now:%H-%M-%S}
  # dir: scratch/logs/training/multiruns/${run_name}/${now:%Y-%m-%d}_${now:%H-%M-%S}
  # subdir: ${hydra.job.num}
  subdir: ${hydra.job.override_dirname}

# you can set here environment variables that are universal for all users
job:
  env_set:
    CUDA_DEVICE_ORDER: "PCI_BUS_ID"
    HYDRA_FULL_ERROR: "1"
  config:
    override_dirname:
      exclude_keys:
        - ckpt_path
        - datamodule
        - datamodule.data_dir
        - datamodule.batch_size
        - datamodule.dataset.properties_list
        - datamodule.num_samples.test
        - datamodule.num_samples.train
        - datamodule.num_samples.valid
        - datamodule.start_idx.test
        - datamodule.start_idx.train
        - datamodule.start_idx.valid
        - datamodule.load_dataset
        - datamodule.save_dataset
        - logger.wandb.tags
        - model.optimizer
        - model.pl_model_ckpt_path
        - model.additional_logger.logging_interval
        - model.linear_steps
        - model.wait_steps
        - model/optimizer
        - model/scheduler_config
        - model
        - callbacks
        - callbacks.model_checkpoint.monitor
        - callbacks.early_stopping
        - callbacks.visualization_callback
        - model.encoder.resolution_dim=64
        - trainer.max_epochs
        - datamodule.dataset.z_dim
        - datamodule.n_balls
        # - model.ball_matching
        - model.disentangle_z_dim
        - model.double_matching
        - model.encoder.n_channels
        - model.encoder.slot_size
        - model.encoder_freeze
        - model.known_action
        - model.known_mechanism
        # - model.latent_matching
        # - model.optimizer.lr
        - model.pair_recons
        - model.rm_background_in_matching
        - model.use_all_balls_mcc
        - model.w_latent_loss
        - model.w_recons_loss
        # - model.z_dim=5

# Set cuda visible devices from command line: export CUDA_VISIBLE_DEVICES=0;python evaluate_kilt_dataset.py
# Or python run.py +hydra.job.env_set.CUDA_VISIBLE_DEVICES="3'
