dataset_target: src.datamodule.inertia_balls_dataset_all_properties_sparse.InertialBallAllPropertiesSparseOffset
z_dim: 2
properties_list: ["y","s"] # can be any subset of ["x","y","c","s"]
signed: False
injective: False
same_color: False
output_sparse_offsets: False
random_coordinates: True

dataset_parameters:
  train:
    dataset:
      _target_: ${datamodule.dataset.dataset_target}
      human_mode: False
      n_balls: ${datamodule.n_balls}
      split: "train"
      seed: ${datamodule.seed}
      num_samples: ${datamodule.num_samples.train}
      color_selection: ${datamodule.color_selection}
      injective: ${datamodule.dataset.injective}
      same_color: ${datamodule.dataset.same_color}
      offset_x: 0.2 # x coordinate offset abs value
      offset_y: ${datamodule.dataset.dataset_parameters.train.dataset.offset_x}
      output_sparse_offsets: ${datamodule.dataset.output_sparse_offsets}
      random_coordinates: ${datamodule.dataset.random_coordinates}
      signed: ${datamodule.dataset.signed}
      z_dim: ${datamodule.dataset.z_dim}
      properties_list: ${datamodule.dataset.properties_list}
      # shape and colour are categorical and can only be incremented one item in their respective lists
      ball_radius: 0.08

    dataloader:
      batch_size: ${datamodule.batch_size}
      num_workers: ${datamodule.num_workers}
      shuffle: ${datamodule.shuffle}
      drop_last: ${datamodule.drop_last}

  valid:
    dataset:
      _target_: ${datamodule.dataset.dataset_target}
      human_mode: False
      n_balls: ${datamodule.n_balls}
      split: "valid"
      seed: ${datamodule.seed}
      num_samples: ${datamodule.num_samples.valid}
      color_selection: ${datamodule.color_selection}
      injective: ${datamodule.dataset.injective}
      same_color: ${datamodule.dataset.same_color}
      offset_x: ${datamodule.dataset.dataset_parameters.train.dataset.offset_x} # x coordinate offset abs value
      offset_y: ${datamodule.dataset.dataset_parameters.valid.dataset.offset_x}
      output_sparse_offsets: ${datamodule.dataset.output_sparse_offsets}
      random_coordinates: ${datamodule.dataset.random_coordinates}
      signed: ${datamodule.dataset.signed}
      z_dim: ${datamodule.dataset.z_dim}
      properties_list: ${datamodule.dataset.properties_list}
      # shape and colour are categorical and can only be incremented one item in their respective lists
      ball_radius: ${datamodule.dataset.dataset_parameters.train.dataset.ball_radius}

    dataloader:
      batch_size: ${datamodule.batch_size}
      num_workers: ${datamodule.num_workers}
      shuffle: ${datamodule.shuffle}
      drop_last: ${datamodule.drop_last}

  test:
    dataset:
      _target_: ${datamodule.dataset.dataset_target}
      human_mode: False
      n_balls: ${datamodule.n_balls}
      split: "test"
      seed: ${datamodule.seed}
      num_samples: ${datamodule.num_samples.test}
      color_selection: ${datamodule.color_selection}
      injective: ${datamodule.dataset.injective}
      same_color: ${datamodule.dataset.same_color}
      offset_x: ${datamodule.dataset.dataset_parameters.train.dataset.offset_x} # x coordinate offset abs value
      offset_y: ${datamodule.dataset.dataset_parameters.test.dataset.offset_x}
      output_sparse_offsets: ${datamodule.dataset.output_sparse_offsets}
      random_coordinates: ${datamodule.dataset.random_coordinates}
      signed: ${datamodule.dataset.signed}
      z_dim: ${datamodule.dataset.z_dim}
      properties_list: ${datamodule.dataset.properties_list}
      # shape and colour are categorical and can only be incremented one item in their respective lists
      ball_radius: ${datamodule.dataset.dataset_parameters.train.dataset.ball_radius}
      
    dataloader:
      batch_size: ${datamodule.batch_size}
      num_workers: ${datamodule.num_workers}
      shuffle: ${datamodule.shuffle}
      drop_last: ${datamodule.drop_last}
